name: movies-deck

image-dock:
  component: "@serverless/website"
  region: ${env.REGION}
  inputs:
    code:
      src: ./build
    bucketName: ${env.BUCKET_NAME}
    domain: movies-deck.smilegupta.tech
